/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
import service.*;
import model.*;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author Luis Felipe Monteiro
 */
public class trabalhoInterface extends javax.swing.JFrame {
        String configcam;
        String testecam;
        String indexmapeamento;
        String indexsubstituicao;
        Long indexconjunto;
    /**
     * Creates new form trabalhoInterface
     */
    public trabalhoInterface() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        configstring = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        testestring = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mapeamentos = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        substituicoes = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        conjuntos = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        hitLabel = new javax.swing.JLabel();
        missLabel = new javax.swing.JLabel();
        taxahitLabel = new javax.swing.JLabel();
        taxaerroLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("selecione o arquivo de configuracao:");

        jButton1.setText("selecionar config");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        configstring.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        configstring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configstringActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("selecione o arquivo de teste:");

        jButton2.setText("selecionar teste");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        testestring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testestringActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("selecione o tipo de mapeamento:");

        mapeamentos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "mapeamento direto", "mapeamento associativo", "mapeamento associativo em conjunto" }));
        mapeamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mapeamentosActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("selecione o metodo de substituição:");

        substituicoes.setMaximumRowCount(4);
        substituicoes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "random", "fifo", "lfu", "lru" }));
        substituicoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                substituicoesActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Yu Gothic Medium", 1, 36)); // NOI18N
        jLabel5.setText("Simulador De Memoria Cache");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("digite a quantidade de linhas por conjunto base 2:");

        conjuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conjuntosActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jButton3.setText("iniciar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        hitLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hitLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        hitLabel.setText("Hits : 0");
        hitLabel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                hitLabelAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        missLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        missLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        missLabel.setText("Misses: 0");
        missLabel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                missLabelAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        taxahitLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        taxahitLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        taxahitLabel.setText("Taxa de Hit: 0.0");
        taxahitLabel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                taxahitLabelAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        taxaerroLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        taxaerroLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        taxaerroLabel.setText("Taxa de Erros: 0.0");
        taxaerroLabel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                taxaerroLabelAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(144, 144, 144))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(117, 117, 117))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(95, 95, 95)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(mapeamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 186, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(configstring)
                                            .addComponent(testestring)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(conjuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(71, 71, 71))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(82, 82, 82)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(taxaerroLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(taxahitLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(missLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(hitLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(40, 40, 40))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(substituicoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(180, 180, 180)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(configstring, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton2)
                    .addComponent(testestring, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mapeamentos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(substituicoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(conjuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hitLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(missLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(taxahitLabel)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(taxaerroLabel)))
                .addGap(32, 32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser fc1 = new JFileChooser();
        fc1.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc1.showOpenDialog(this);
        File f = fc1.getSelectedFile();
        configstring.setText(f.getPath());
        configcam = configstring.getText();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void configstringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configstringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_configstringActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser fc = new JFileChooser(); //cria um objeto do tipo filechooser e instancia este objeto
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY); //apenas permite que arquivos sejam selecionados
        fc.showOpenDialog(this);//abre a selecao de arquivos
        File f = fc.getSelectedFile(); //pega o arquivo selecionado.
        testestring.setText(f.getPath()); //passa o caminho do arquivo selecionado para o meu campo de texto configstring.
        testecam = testestring.getText();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void mapeamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mapeamentosActionPerformed
        indexmapeamento = (String)mapeamentos.getSelectedItem();
    }//GEN-LAST:event_mapeamentosActionPerformed

    private void substituicoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_substituicoesActionPerformed
        indexsubstituicao = (String)substituicoes.getSelectedItem();
    }//GEN-LAST:event_substituicoesActionPerformed

    private void conjuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conjuntosActionPerformed
        try {
        // Obtém o texto do campo de entrada e converte para Long
        indexconjunto = Long.parseLong(conjuntos.getText());
  
    } catch (NumberFormatException e) {
        // Se houver um erro na conversão, você pode tratar aqui (por exemplo, exibir uma mensagem de erro)
        System.out.println("Por favor, insira um número válido.");
    }
    }//GEN-LAST:event_conjuntosActionPerformed

    private void testestringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testestringActionPerformed
        testecam = (String)testestring.getSelectedText();
    }//GEN-LAST:event_testestringActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(indexmapeamento.equals("mapeamento direto")){
            mapDireto md = new mapDireto(testecam,configcam);
            md.enderecamentoDireto();
            hitLabel.setText("Hits: " + md.getHit());
            missLabel.setText("Misses: " + md.getMiss());
            taxahitLabel.setText("Taxa de Hit: " + md.getTaxahit());
            taxaerroLabel.setText("Taxa de Erro: " + md.getTaxaerro());
        }else if(indexmapeamento.equals("mapeamento associativo")){
        switch(indexsubstituicao){
            case "random":
                mapAssociativo aRandom = new mapAssociativo(testecam,configcam);
                aRandom.randomAssociativo();
               hitLabel.setText("Hits: " + aRandom.getHit());
               missLabel.setText("Misses: " + aRandom.getMiss());
               taxahitLabel.setText("Taxa de Hit: " + aRandom.getTaxahit());
               taxaerroLabel.setText("Taxa de Erro: " + aRandom.getTaxaerro());
                break;
            case "fifo":
                mapAssociativo aFifo = new mapAssociativo(testecam,configcam);
                aFifo.fifoAssociativo();
                hitLabel.setText("Hits: " + aFifo.getHit());
               missLabel.setText("Misses: " + aFifo.getMiss());
               taxahitLabel.setText("Taxa de Hit: " + aFifo.getTaxahit());
               taxaerroLabel.setText("Taxa de Erro: " + aFifo.getTaxaerro());
                break;
            case "lru":
                mapAssociativo aLru = new mapAssociativo(testecam,configcam);
               aLru.lruAssociativo();
                hitLabel.setText("Hits: " + aLru.getHit());
               missLabel.setText("Misses: " + aLru.getMiss());
               taxahitLabel.setText("Taxa de Hit: " + aLru.getTaxahit());
               taxaerroLabel.setText("Taxa de Erro: " + aLru.getTaxaerro());
               break;
            case "lfu":
                mapAssociativo aLfu = new mapAssociativo(testecam,configcam);
                aLfu.lfuAssociativo();
                hitLabel.setText("Hits: " + aLfu.getHit());
               missLabel.setText("Misses: " + aLfu.getMiss());
               taxahitLabel.setText("Taxa de Hit: " + aLfu.getTaxahit());
               taxaerroLabel.setText("Taxa de Erro: " + aLfu.getTaxaerro());
                break;
            default:
                break;
        }
        }else if(indexmapeamento.equals("mapeamento associativo em conjunto")){
         switch(indexsubstituicao){
            case "random":
                mapAssociativoConjunto aCRandom = new mapAssociativoConjunto(indexconjunto,testecam,configcam);
                aCRandom.conjuntoRandom();
                hitLabel.setText("Hits: " + aCRandom.getHit());
                missLabel.setText("Misses: " + aCRandom.getMiss());
                taxahitLabel.setText("Taxa de Hit: " + aCRandom.getTaxahit());
                taxaerroLabel.setText("Taxa de Erro: " + aCRandom.getTaxaerro());
                break;
            case "fifo":
                mapAssociativoConjunto aCFifo = new mapAssociativoConjunto(indexconjunto,testecam,configcam);
                aCFifo.conjuntoFifo();
                hitLabel.setText("Hits: " + aCFifo.getHit());
                missLabel.setText("Misses: " + aCFifo.getMiss());
                taxahitLabel.setText("Taxa de Hit: " + aCFifo.getTaxahit());
                taxaerroLabel.setText("Taxa de Erro: " + aCFifo.getTaxaerro());
                break;
            case "lru":
                mapAssociativoConjunto aCLru = new mapAssociativoConjunto(indexconjunto,testecam,configcam);
               aCLru.cojuntoLru();
               hitLabel.setText("Hits: " + aCLru.getHit());
               missLabel.setText("Misses: " + aCLru.getMiss());
               taxahitLabel.setText("Taxa de Hit: " + aCLru.getTaxahit());
               taxaerroLabel.setText("Taxa de Erro: " + aCLru.getTaxaerro());
               break;
            case "lfu":
                mapAssociativoConjunto aCLfu = new mapAssociativoConjunto(indexconjunto,testecam,configcam);
                aCLfu.conjuntoLfu();
               hitLabel.setText("Hits: " + aCLfu.getHit());
               missLabel.setText("Misses: " + aCLfu.getMiss());
               taxahitLabel.setText("Taxa de Hit: " + aCLfu.getTaxahit());
               taxaerroLabel.setText("Taxa de Erro: " + aCLfu.getTaxaerro());
                break;
            default:
                break;
        }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void hitLabelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_hitLabelAncestorAdded
    }//GEN-LAST:event_hitLabelAncestorAdded

    private void missLabelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_missLabelAncestorAdded
    }//GEN-LAST:event_missLabelAncestorAdded

    private void taxahitLabelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_taxahitLabelAncestorAdded
    }//GEN-LAST:event_taxahitLabelAncestorAdded

    private void taxaerroLabelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_taxaerroLabelAncestorAdded
    }//GEN-LAST:event_taxaerroLabelAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(trabalhoInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(trabalhoInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(trabalhoInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(trabalhoInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new trabalhoInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField configstring;
    private javax.swing.JTextField conjuntos;
    private javax.swing.JLabel hitLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> mapeamentos;
    private javax.swing.JLabel missLabel;
    private javax.swing.JComboBox<String> substituicoes;
    private javax.swing.JLabel taxaerroLabel;
    private javax.swing.JLabel taxahitLabel;
    private javax.swing.JTextField testestring;
    // End of variables declaration//GEN-END:variables
}
